// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// AuthHandler is an autogenerated mock type for the AuthHandler type
type AuthHandler struct {
	mock.Mock
}

// Login provides a mock function with given fields: context
func (_m *AuthHandler) Login(context *gin.Context) {
	_m.Called(context)
}

// Logout provides a mock function with given fields: context
func (_m *AuthHandler) Logout(context *gin.Context) {
	_m.Called(context)
}

// Register provides a mock function with given fields: context
func (_m *AuthHandler) Register(context *gin.Context) {
	_m.Called(context)
}

// NewAuthHandler creates a new instance of AuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthHandler {
	mock := &AuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
