// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// TodoHandler is an autogenerated mock type for the TodoHandler type
type TodoHandler struct {
	mock.Mock
}

// CreateTodo provides a mock function with given fields: context
func (_m *TodoHandler) CreateTodo(context *gin.Context) {
	_m.Called(context)
}

// DeleteTodo provides a mock function with given fields: context
func (_m *TodoHandler) DeleteTodo(context *gin.Context) {
	_m.Called(context)
}

// ReadTodo provides a mock function with given fields: context
func (_m *TodoHandler) ReadTodo(context *gin.Context) {
	_m.Called(context)
}

// UpdateTodo provides a mock function with given fields: context
func (_m *TodoHandler) UpdateTodo(context *gin.Context) {
	_m.Called(context)
}

// NewTodoHandler creates a new instance of TodoHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoHandler {
	mock := &TodoHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
